### ISSUE TITLE
k8s-snapshots stopped working after upgrading to Kubernetes 1.20

### ISSUE THREAD

**Issue by tokyowizard** [miracle2k/k8s-snapshots#102]
`k8s-snapshots` has been running well in Kubernetes 1.19.

We upgraded our EKS cluster to Kubernetes [1.20.4](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) and `k8s-snapshots` stopped working. Snapshots haven't been created since the upgrade. The logs in the k8s-snapshots pod has the following error message:
```
2021-06-02T02:08:33.392863Z foreign                        [asyncio] message=Exception in callback StreamReader._ensure_running.<locals>.cb(<Task finishe...('selfLink',)>) at /usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py:116
handle: <Handle StreamReader._ensure_running.<locals>.cb(<Task finishe...('selfLink',)>) at /usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py:116> severity=ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 122, in cb
    raise task.exception()
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 107, in _iterate_task
    async for item in self.iterable:
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 455, in get_rules
    async for rules in rules_from_kubernetes(ctx):
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 377, in rules_from_kubernetes
    rule = await rule_from_persistent_volume_claim(ctx, resource)
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 296, in rule_from_persistent_volume_claim
    source=volume_claim
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/rule.py", line 179, in rule_from_pv
    source=volume.obj['metadata']['selfLink'],
KeyError: 'selfLink'
```

**Comment by miracle2k** [comment]
Dup of #104, fixed in master.
