### ISSUE TITLE
Feature Request: Support Digital Ocean

### ISSUE THREAD

**Issue by rimusz** [miracle2k/k8s-snapshots#17]

**Comment by miracle2k** [comment]
The master branch now supports pluggable backends, and has implementations for AWS and GCloud. If anyone wants to take this on, it shouldn't be too hard to add.

**Comment by rbren** [comment]
Should this be closed? The README says DO is now supported, though with `latest` I'm seeing `unsupported` errors:

```
k8s-snapshots-5c4b5778d8-xjwfc k8s-snapshots 2020-01-22T21:21:19.720417Z volume-event.received          [k8s_snapshots.core] event_object={'kind': 'PersistentVolume', 'apiVersion': 'v1', 'metadata': {'name': 'pvc-1dcb642a-2174-4d99-902d-0b2eebf38388', 'selfLink': '/api/v1/persistentvolumes/pvc-1dcb642a-2174-4d99-902d-0b2eebf38388', 'uid': 'e522bcb1-ee4b-4196-aaff-fb10b2ad86df', 'resourceVersion': '791643', 'creationTimestamp': '2020-01-22T20:43:49Z', 'annotations': {'backup.kubernetes.io/deltas': 'P1D P30D', 'pv.kubernetes.io/provisioned-by': 'dobs.csi.digitalocean.com'}, 'finalizers': ['kubernetes.io/pv-protection', 'external-attacher/dobs-csi-digitalocean-com']}, 'spec': {'capacity': {'storage': '8Gi'}, 'csi': {'driver': 'dobs.csi.digitalocean.com', 'volumeHandle': 'e448af3f-3d57-11ea-9741-0a58ac144403', 'fsType': 'ext4', 'volumeAttributes': {'storage.kubernetes.io/csiProvisionerIdentity': '1579441603391-8081-dobs.csi.digitalocean.com'}}, 'accessModes': ['ReadWriteOnce'], 'claimRef': {'kind': 'PersistentVolumeClaim', 'namespace': 'ghost', 'name': 'data-ghost-mariadb-0', 'uid': '1dcb642a-2174-4d99-902d-0b2eebf38388', 'apiVersion': 'v1', 'resourceVersion': '785164'}, 'persistentVolumeReclaimPolicy': 'Retain', 'storageClassName': 'do-block-storage', 'volumeMode': 'Filesystem'}, 'status': {'phase': 'Bound'}} event_type=MODIFIED message=volume-event.received: event_type='MODIFIED', event_object.metadata.name='pvc-1dcb642a-2174-4d99-902d-0b2eebf38388' severity=INFO
k8s-snapshots-5c4b5778d8-xjwfc k8s-snapshots 2020-01-22T21:21:19.721833Z volume.unsupported             [k8s_snapshots.core] message=volume.unsupported: volume.metadata.name='pvc-1dcb642a-2174-4d99-902d-0b2eebf38388' resource=<PersistentVolume pvc-1dcb642a-2174-4d99-902d-0b2eebf38388> severity=INFO structured_error=[{'type': 'UnsupportedVolume', 'message': 'Unsupported volume', 'data': {'volume': <PersistentVolume pvc-1dcb642a-2174-4d99-902d-0b2eebf38388>}, 'readable': ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 241, in rule_from_persistent_volume\n    return await rule_from_pv(ctx, volume, deltas, source=volume)\n', '  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/rule.py", line 161, in rule_from_pv\n    volume=volume\n', "k8s_snapshots.errors.UnsupportedVolume: UnsupportedVolume: Unsupported volume {'volume': <PersistentVolume pvc-1dcb642a-2174-4d99-902d-0b2eebf38388>}\n"]}] volume={'kind': 'PersistentVolume', 'apiVersion': 'v1', 'metadata': {'name': 'pvc-1dcb642a-2174-4d99-902d-0b2eebf38388', 'selfLink': '/api/v1/persistentvolumes/pvc-1dcb642a-2174-4d99-902d-0b2eebf38388', 'uid': 'e522bcb1-ee4b-4196-aaff-fb10b2ad86df', 'resourceVersion': '791643', 'creationTimestamp': '2020-01-22T20:43:49Z', 'annotations': {'backup.kubernetes.io/deltas': 'P1D P30D', 'pv.kubernetes.io/provisioned-by': 'dobs.csi.digitalocean.com'}, 'finalizers': ['kubernetes.io/pv-protection', 'external-attacher/dobs-csi-digitalocean-com']}, 'spec': {'capacity': {'storage': '8Gi'}, 'csi': {'driver': 'dobs.csi.digitalocean.com', 'volumeHandle': 'e448af3f-3d57-11ea-9741-0a58ac144403', 'fsType': 'ext4', 'volumeAttributes': {'storage.kubernetes.io/csiProvisionerIdentity': '1579441603391-8081-dobs.csi.digitalocean.com'}}, 'accessModes': ['ReadWriteOnce'], 'claimRef': {'kind': 'PersistentVolumeClaim', 'namespace': 'ghost', 'name': 'data-ghost-mariadb-0', 'uid': '1dcb642a-2174-4d99-902d-0b2eebf38388', 'apiVersion': 'v1', 'resourceVersion': '785164'}, 'persistentVolumeReclaimPolicy': 'Retain', 'storageClassName': 'do-block-storage', 'volumeMode': 'Filesystem'}, 'status': {'phase': 'Bound'}} volume_name=pvc-1dcb642a-2174-4d99-902d-0b2eebf38388
```

**Comment by henkvanramshorst** [comment]
What's the status on this? I tried to use it with Digital Ocean, and also got unsupported errors just like @rbren.

**Comment by miracle2k** [comment]
It turns out the latest tag build was failing for a while on Docker Hub unnoticed. This is now fixed, and with any luck, the current latest image has DO support enabled.
