### ISSUE TITLE
Exception in callback

### ISSUE THREAD

**Issue by JorritSalverda** [miracle2k/k8s-snapshots#2]
I get the following error in one of my clusters:

```
Exception in callback combine.<locals>.cb(<Task cancell...cutils.py:16>>) at /app/asyncutils.py:24
handle: <Handle combine.<locals>.cb(<Task cancell...cutils.py:16>>) at /app/asyncutils.py:24>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/app/asyncutils.py", line 25, in cb
    if task.exception():
concurrent.futures._base.CancelledError
```

I'm trying to find out if one of the pv's has some unexpected data, but there's a lot of them so might be hard. Any pointers that could help tackle the issue?

Prior to this error the following debug messages were logged:

```
[2017-01-27 14:12:17.913451] DEBUG: daemon: Event in persistent volume stream: WatchEvent(type='ADDED', object=<PersistentVolume pvc-d2451259-e416-11e6-a7ce-42010af00060>)
[2017-01-27 14:12:17.913579] DEBUG: daemon: Volume pvc-d2451259-e416-11e6-a7ce-42010af00060 does not define backup deltas (via backup.kubernetes.io/deltas)
```

**Comment by miracle2k** [comment]
I'm closing this for now, since the whole code has been refactored, so hopefully this bug is gone with it (not: new image not yet released).
