### ISSUE TITLE
TypeError: object of type 'Rule' has no len()

### ISSUE THREAD

**Issue by saward** [miracle2k/k8s-snapshots#20]
Hi,

Using the docker image from https://hub.docker.com/r/elsdoerfer/k8s-snapshots/, my container no longer starts.  It now shows the error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/k8s_snapshots/__main__.py", line 101, in <module>
    sys.exit(main() or 0)
  File "/app/k8s_snapshots/__main__.py", line 15, in main
    config = k8s_snapshots.config.from_environ()
  File "/app/k8s_snapshots/config.py", line 128, in from_environ
    config.update(read_volume_config())
  File "/app/k8s_snapshots/config.py", line 181, in read_volume_config
    config['rules'] = list(filter(bool, map(read_volume, volumes)))
  File "/app/k8s_snapshots/config.py", line 175, in read_volume
    _log.info(events.Rule.ADDED_FROM_CONFIG, rule=rule)
  File "/usr/local/lib/python3.6/site-packages/structlog/_base.py", line 176, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/usr/local/lib/python3.6/site-packages/structlog/_base.py", line 136, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/usr/local/lib/python3.6/site-packages/structlog/dev.py", line 181, in __call__
    event = _pad(event, self._pad_event) + self._styles.reset + " "
  File "/usr/local/lib/python3.6/site-packages/structlog/dev.py", line 36, in _pad
    missing = l - len(s)
TypeError: object of type 'Rule' has no len()
```

Any idea what this error is caused by?  Has the syntax for anything changed?  Just to give an example of what my config looks like

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-snapshots
  labels:
    app: k8s-snapshots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-snapshots
  template:
    metadata:
      labels:
        app: k8s-snapshots
    spec:
      containers:
        - image: elsdoerfer/k8s-snapshots
          name: k8s-snapshots
          env:
          - name: GCLOUD_PROJECT
            value: <hidden>
          - name: VOLUMES
            value: "wordpress"
          - name: VOLUME_WORDPRESS_DELTAS
            value: "6h 1d 30d 180d"
          - name: VOLUME_WORDPRESS_ZONE
            value: "asia-east1-a"
...<more here>...
          - name: GCLOUD_JSON_KEYFILE_STRING
            valueFrom:
              secretKeyRef:
                name: snapshots-service-account
                key: snapshots-service-account.json
```

**Comment by miracle2k** [comment]
The approach of setting of volumes manually using ``VOLUMES`` is currently broken. It's been on  my list to fix. Sorry about that  :(

**Comment by saward** [comment]
I'll keep an eye on this issue for in case you fix it :)  In the meantime, going to the docker image tagged v0.1 seems to have restored backups.  No idea what I've lost from going back that far though, since the image is 6 months old.
