### ISSUE TITLE
Snapshotting stopped working: googleapiclient.errors.HttpError

### ISSUE THREAD

**Issue by mcnijman** [miracle2k/k8s-snapshots#57]
Hi,

Thanks for this great project. All the annotated pvc's in my project stopped getting snapshots since may 10 and the k8s-snapshots instance is giving the error below, any idea why or how this can happen?

```Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 112, in make_backup File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 215, in poll_for_status File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 304, in get_snapshot_status File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 12, in run_in_executor File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 304, in <lambda> File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/backends/google.py", line 250, in get_snapshot_status File "/usr/local/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper return wrapped(*args, **kwargs) File "/usr/local/lib/python3.6/site-packages/googleapiclient/http.py", line 840, in execute raise HttpError(resp, content, uri=self.uri) googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/PROJECT_NAME/global/snapshots/SNAPSHOT_NAME?alt=json returned "The resource 'projects/PROJECT_NAME/global/snapshots/SNAPSHOT_NAME' was not found">```

Thanks

**Comment by mcnijman** [comment]
My bad, it had something to do with my snapshot quota.

**Comment by mcnijman** [comment]
This is fixed in #51
